export type BibleBook = {
  name: string;
  slug: string;
  chapters: number;
  testament: "Old Testament" | "New Testament";
};

export const BIBLE_BOOKS: BibleBook[] = [
  { name: "Genesis", slug: "genesis", chapters: 50, testament: "Old Testament" },
  { name: "Exodus", slug: "exodus", chapters: 40, testament: "Old Testament" },
  { name: "Leviticus", slug: "leviticus", chapters: 27, testament: "Old Testament" },
  { name: "Numbers", slug: "numbers", chapters: 36, testament: "Old Testament" },
  { name: "Deuteronomy", slug: "deuteronomy", chapters: 34, testament: "Old Testament" },
  { name: "Joshua", slug: "joshua", chapters: 24, testament: "Old Testament" },
  { name: "Judges", slug: "judges", chapters: 21, testament: "Old Testament" },
  { name: "Ruth", slug: "ruth", chapters: 4, testament: "Old Testament" },
  { name: "1 Samuel", slug: "1 samuel", chapters: 31, testament: "Old Testament" },
  { name: "2 Samuel", slug: "2 samuel", chapters: 24, testament: "Old Testament" },
  { name: "1 Kings", slug: "1 kings", chapters: 22, testament: "Old Testament" },
  { name: "2 Kings", slug: "2 kings", chapters: 25, testament: "Old Testament" },
  { name: "1 Chronicles", slug: "1 chronicles", chapters: 29, testament: "Old Testament" },
  { name: "2 Chronicles", slug: "2 chronicles", chapters: 36, testament: "Old Testament" },
  { name: "Ezra", slug: "ezra", chapters: 10, testament: "Old Testament" },
  { name: "Nehemiah", slug: "nehemiah", chapters: 13, testament: "Old Testament" },
  { name: "Esther", slug: "esther", chapters: 10, testament: "Old Testament" },
  { name: "Job", slug: "job", chapters: 42, testament: "Old Testament" },
  { name: "Psalms", slug: "psalms", chapters: 150, testament: "Old Testament" },
  { name: "Proverbs", slug: "proverbs", chapters: 31, testament: "Old Testament" },
  { name: "Ecclesiastes", slug: "ecclesiastes", chapters: 12, testament: "Old Testament" },
  { name: "Song of Solomon", slug: "song of solomon", chapters: 8, testament: "Old Testament" },
  { name: "Isaiah", slug: "isaiah", chapters: 66, testament: "Old Testament" },
  { name: "Jeremiah", slug: "jeremiah", chapters: 52, testament: "Old Testament" },
  { name: "Lamentations", slug: "lamentations", chapters: 5, testament: "Old Testament" },
  { name: "Ezekiel", slug: "ezekiel", chapters: 48, testament: "Old Testament" },
  { name: "Daniel", slug: "daniel", chapters: 12, testament: "Old Testament" },
  { name: "Hosea", slug: "hosea", chapters: 14, testament: "Old Testament" },
  { name: "Joel", slug: "joel", chapters: 3, testament: "Old Testament" },
  { name: "Amos", slug: "amos", chapters: 9, testament: "Old Testament" },
  { name: "Obadiah", slug: "obadiah", chapters: 1, testament: "Old Testament" },
  { name: "Jonah", slug: "jonah", chapters: 4, testament: "Old Testament" },
  { name: "Micah", slug: "micah", chapters: 7, testament: "Old Testament" },
  { name: "Nahum", slug: "nahum", chapters: 3, testament: "Old Testament" },
  { name: "Habakkuk", slug: "habakkuk", chapters: 3, testament: "Old Testament" },
  { name: "Zephaniah", slug: "zephaniah", chapters: 3, testament: "Old Testament" },
  { name: "Haggai", slug: "haggai", chapters: 2, testament: "Old Testament" },
  { name: "Zechariah", slug: "zechariah", chapters: 14, testament: "Old Testament" },
  { name: "Malachi", slug: "malachi", chapters: 4, testament: "Old Testament" },
  { name: "Matthew", slug: "matthew", chapters: 28, testament: "New Testament" },
  { name: "Mark", slug: "mark", chapters: 16, testament: "New Testament" },
  { name: "Luke", slug: "luke", chapters: 24, testament: "New Testament" },
  { name: "John", slug: "john", chapters: 21, testament: "New Testament" },
  { name: "Acts", slug: "acts", chapters: 28, testament: "New Testament" },
  { name: "Romans", slug: "romans", chapters: 16, testament: "New Testament" },
  { name: "1 Corinthians", slug: "1 corinthians", chapters: 16, testament: "New Testament" },
  { name: "2 Corinthians", slug: "2 corinthians", chapters: 13, testament: "New Testament" },
  { name: "Galatians", slug: "galatians", chapters: 6, testament: "New Testament" },
  { name: "Ephesians", slug: "ephesians", chapters: 6, testament: "New Testament" },
  { name: "Philippians", slug: "philippians", chapters: 4, testament: "New Testament" },
  { name: "Colossians", slug: "colossians", chapters: 4, testament: "New Testament" },
  { name: "1 Thessalonians", slug: "1 thessalonians", chapters: 5, testament: "New Testament" },
  { name: "2 Thessalonians", slug: "2 thessalonians", chapters: 3, testament: "New Testament" },
  { name: "1 Timothy", slug: "1 timothy", chapters: 6, testament: "New Testament" },
  { name: "2 Timothy", slug: "2 timothy", chapters: 4, testament: "New Testament" },
  { name: "Titus", slug: "titus", chapters: 3, testament: "New Testament" },
  { name: "Philemon", slug: "philemon", chapters: 1, testament: "New Testament" },
  { name: "Hebrews", slug: "hebrews", chapters: 13, testament: "New Testament" },
  { name: "James", slug: "james", chapters: 5, testament: "New Testament" },
  { name: "1 Peter", slug: "1 peter", chapters: 5, testament: "New Testament" },
  { name: "2 Peter", slug: "2 peter", chapters: 3, testament: "New Testament" },
  { name: "1 John", slug: "1 john", chapters: 5, testament: "New Testament" },
  { name: "2 John", slug: "2 john", chapters: 1, testament: "New Testament" },
  { name: "3 John", slug: "3 john", chapters: 1, testament: "New Testament" },
  { name: "Jude", slug: "jude", chapters: 1, testament: "New Testament" },
  { name: "Revelation", slug: "revelation", chapters: 22, testament: "New Testament" },
];

export function getBookBySlug(slug: string) {
  return BIBLE_BOOKS.find((book) => book.slug === slug);
}
